### ISSUE TITLE
Documentation for the CSR fields?

### ISSUE THREAD

**Issue by seandextercrevinn** [antmicro/fastvdma#12]
Hi,

I'm looking for any documentation about the fields of the CSRs in the design. I'm trying to write software to handle the DMA controller in a design with a RISC-V core, and I'm having trouble with understanding which bits of the registers to program. Is there anywhere I can find documentation on what the fields of each register are, and a brief description of their operation?

Thanks

**Comment by piotr-binkowski** [comment]
Hi,

You can take a look at documentation changes in #13 to get more information about CSR fields
