### ISSUE TITLE
Getting error wile running "make test/testall" in master branch

### ISSUE THREAD

**Issue by kushalc2021** [antmicro/fastvdma#19]
Cloned master branch and installed dependencies (sbt, scala, java & imagemagik) as described in Readme. After that while running "make test/testall" got error as shown in below snapshot:
![image](https://user-images.githubusercontent.com/81458682/198602972-f880036b-36f8-436a-ba45-53b9f375bc75.png)

**Comment by kgugala** [comment]
@kushalc2021 thanks for reporting this, seems that README got out of date - we'll fix this.

In the meantime you can follow test script used in CI https://github.com/antmicro/fastvdma/blob/master/.github/scripts/test.sh. This will allow you to run the checks.

**Comment by kgugala** [comment]
The readme has been updated

**Comment by kushalc2021** [comment]
Issue resolved
